### ISSUE TITLE
TypeError: Argument 'other' has incorrect type 

### ISSUE THREAD

**Issue by karel-brinda** [karel-brinda/samsift#19]
```
 samsift -i a.sam -0 'r="a"' -f 'a!=QNAME' -c 'a=QNAME'
```

```
samsift] 2018-03-16 15:01:19 SAMsift is starting.
Traceback (most recent call last):
  File "/Users/karel/miniconda/bin/samsift", line 6, in <module>
    sys.exit(samsift.samsift.main())
  File "/Users/karel/miniconda/lib/python3.6/site-packages/samsift/samsift.py", line 418, in main
    sam_sift.run()
  File "/Users/karel/miniconda/lib/python3.6/site-packages/samsift/samsift.py", line 283, in run
    self.process_alignment(alignment)
  File "/Users/karel/miniconda/lib/python3.6/site-packages/samsift/samsift.py", line 248, in process_alignment
    self._filter()
  File "/Users/karel/miniconda/lib/python3.6/site-packages/samsift/samsift.py", line 182, in _filter
(END)    self.passes=eval(self.filter, self.vardict)
  File "<string>", line 1, in <module>
TypeError: Argument 'other' has incorrect type (expected pysam.libcalignedsegment.AlignedSegment, got str)
```

**Comment by karel-brinda** [comment]
Typo in the command.
