### ISSUE TITLE
Python keywords cause errors when used as tag names

### ISSUE THREAD

**Issue by karel-brinda** [karel-brinda/samsift#24]
```
$ samsift -i filtered.sam -f 'is>50'
...
Traceback (most recent call last):
  File "/home/kb219/miniconda/bin/samsift", line 11, in <module>
    sys.exit(main())
  File "/home/kb219/miniconda/lib/python3.6/site-packages/samsift/samsift.py", line 418, in main
    sam_sift.run()
  File "/home/kb219/miniconda/lib/python3.6/site-packages/samsift/samsift.py", line 283, in run
    self.process_alignment(alignment)
  File "/home/kb219/miniconda/lib/python3.6/site-packages/samsift/samsift.py", line 248, in process_alignment
    self._filter()
  File "/home/kb219/miniconda/lib/python3.6/site-packages/samsift/samsift.py", line 182, in _filter
    self.passes=eval(self.filter, self.vardict)
  File "<string>", line 1
    is>50
     ^
SyntaxError: invalid syntax
```

**Comment by karel-brinda** [comment]
Solution:

```bash
samsift -i filtered.sam -f 'locals()["is"]>50'
```
